FAILURE_TASK_NOT_READY = "task_not_ready"
FAILURE_REPOSITORY_CHECKOUT_FAILED = "repository_checkout_failed"
FAILURE_DOCKER_UNAVAILABLE = "docker_unavailable"
FAILURE_SETUP_FAILED = "setup_failed"
FAILURE_BASELINE_TESTS_FAILED = "baseline_tests_failed"
FAILURE_MODEL_PROVIDER_ERROR = "model_provider_error"
FAILURE_MALFORMED_TOOL_CALL = "malformed_tool_call"
FAILURE_UNKNOWN_TOOL = "unknown_tool"
FAILURE_TOOL_ERROR_LIMIT_REACHED = "tool_error_limit_reached"
FAILURE_PATCH_GENERATION_FAILED = "patch_generation_failed"
FAILURE_PATCH_APPLY_FAILED = "patch_apply_failed"
FAILURE_PATCH_QUALITY_BLOCKED = "patch_quality_blocked"
FAILURE_POST_PATCH_TESTS_FAILED = "post_patch_tests_failed"
FAILURE_MAX_STEPS_REACHED = "max_steps_reached"
FAILURE_MAX_REPAIR_ATTEMPTS_REACHED = "max_repair_attempts_reached"
FAILURE_TIMEOUT = "timeout"
FAILURE_CANCELLED = "cancelled"
FAILURE_UNKNOWN = "unknown"

FAILURE_CATEGORIES = frozenset(
    {
        FAILURE_TASK_NOT_READY,
        FAILURE_REPOSITORY_CHECKOUT_FAILED,
        FAILURE_DOCKER_UNAVAILABLE,
        FAILURE_SETUP_FAILED,
        FAILURE_BASELINE_TESTS_FAILED,
        FAILURE_MODEL_PROVIDER_ERROR,
        FAILURE_MALFORMED_TOOL_CALL,
        FAILURE_UNKNOWN_TOOL,
        FAILURE_TOOL_ERROR_LIMIT_REACHED,
        FAILURE_PATCH_GENERATION_FAILED,
        FAILURE_PATCH_APPLY_FAILED,
        FAILURE_PATCH_QUALITY_BLOCKED,
        FAILURE_POST_PATCH_TESTS_FAILED,
        FAILURE_MAX_STEPS_REACHED,
        FAILURE_MAX_REPAIR_ATTEMPTS_REACHED,
        FAILURE_TIMEOUT,
        FAILURE_CANCELLED,
        FAILURE_UNKNOWN,
    }
)
