REVIEW_DECISION_APPROVED = "approved"
REVIEW_DECISION_REJECTED = "rejected"

REVIEW_STATUS_PENDING = "pending"
REVIEW_STATUS_APPROVED = REVIEW_DECISION_APPROVED
REVIEW_STATUS_REJECTED = REVIEW_DECISION_REJECTED

VALID_REVIEW_DECISIONS = {
    REVIEW_DECISION_APPROVED,
    REVIEW_DECISION_REJECTED,
}
