TASK_STATUS_DRAFT = "draft"
TASK_STATUS_READY = "ready"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_ARCHIVED = "archived"

VALID_TASK_STATUSES = {
    TASK_STATUS_DRAFT,
    TASK_STATUS_READY,
    TASK_STATUS_RUNNING,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_ARCHIVED,
}

ALLOWED_TASK_STATUS_TRANSITIONS = {
    TASK_STATUS_DRAFT: {TASK_STATUS_READY, TASK_STATUS_ARCHIVED},
    TASK_STATUS_READY: {TASK_STATUS_RUNNING, TASK_STATUS_ARCHIVED},
    TASK_STATUS_RUNNING: {TASK_STATUS_COMPLETED, TASK_STATUS_FAILED},
    TASK_STATUS_COMPLETED: {TASK_STATUS_ARCHIVED},
    TASK_STATUS_FAILED: {TASK_STATUS_READY, TASK_STATUS_ARCHIVED},
    TASK_STATUS_ARCHIVED: set(),
}
