TEST_PHASE_SETUP = "setup"
TEST_PHASE_BASELINE = "baseline"
TEST_PHASE_POST_PATCH = "post_patch"
TEST_PHASE_LINT = "lint"
TEST_PHASE_FORMAT_CHECK = "format_check"
TEST_PHASE_HIDDEN_EVAL = "hidden_eval"

VALID_TEST_PHASES = {
    TEST_PHASE_SETUP,
    TEST_PHASE_BASELINE,
    TEST_PHASE_POST_PATCH,
    TEST_PHASE_LINT,
    TEST_PHASE_FORMAT_CHECK,
    TEST_PHASE_HIDDEN_EVAL,
}

VISIBLE_TEST_PHASES = {
    TEST_PHASE_SETUP,
    TEST_PHASE_BASELINE,
    TEST_PHASE_POST_PATCH,
    TEST_PHASE_LINT,
    TEST_PHASE_FORMAT_CHECK,
}
