TEST_PHASE_SETUP = "setup"
TEST_PHASE_BASELINE = "baseline"
TEST_PHASE_POST_PATCH = "post_patch"
TEST_PHASE_HIDDEN_EVAL = "hidden_eval"

VALID_TEST_PHASES = {
    TEST_PHASE_SETUP,
    TEST_PHASE_BASELINE,
    TEST_PHASE_POST_PATCH,
    TEST_PHASE_HIDDEN_EVAL,
}

VISIBLE_TEST_PHASES = {
    TEST_PHASE_SETUP,
    TEST_PHASE_BASELINE,
    TEST_PHASE_POST_PATCH,
}
